name: 'KiBot PCB Manufacturing Files'
description: 'Generate PCB manufacturing files and documentation using KiBot'
author: 'massarin'

inputs:
  config-path:
    description: 'Path to KiBot configuration file (defaults to config.kibot.yaml in repo root or action default)'
    required: false
    default: ''
  deploy-to-pages:
    description: 'Deploy generated files to GitHub Pages'
    required: false
    default: 'true'
  pages-branch:
    description: 'Branch to deploy to for GitHub Pages'
    required: false
    default: 'gh-pages'

outputs:
  artifacts-path:
    description: 'Path to generated artifacts'
    value: 'Generated'

runs:
  using: 'composite'
  steps:
    - name: Generate outputs with KiBot
      run: |
        if [ -n "${{ inputs.config-path }}" ]; then
          echo "Using specified config: ${{ inputs.config-path }}"
          kibot -c "${{ inputs.config-path }}"
        elif [ -f config.kibot.yaml ]; then
          echo "Using user's config.kibot.yaml"
          kibot -c config.kibot.yaml
        else
          echo "Using default config from action"
          # Use environment variable instead of github.action_path for better container compatibility
          DEFAULT_CONFIG="${GITHUB_ACTION_PATH}/config.kibot.yaml"
          if [ -f "$DEFAULT_CONFIG" ]; then
            kibot -c "$DEFAULT_CONFIG"
          else
            echo "ERROR: Default config not found at $DEFAULT_CONFIG"
            echo "Action path: $GITHUB_ACTION_PATH"
            echo "Available files in action:"
            ls -la "$GITHUB_ACTION_PATH" 2>/dev/null || echo "Cannot list action directory"
            exit 1
          fi
        fi
      shell: bash

    - name: Create root index
      run: |
        NAVIGATE_FILE=$(ls Generated/Browse/*-navigate.html 2>/dev/null | head -n1)
        if [ -n "$NAVIGATE_FILE" ]; then
          NAVIGATE_FILENAME=$(basename "$NAVIGATE_FILE")
          cat > Generated/index.html << EOF
        <html>
        <head>
        <meta http-equiv="refresh" content="0; Browse/$NAVIGATE_FILENAME"/>
        </head>
        </html>
        EOF
          echo "Created index.html redirecting to Browse/$NAVIGATE_FILENAME"
        else
          echo "No navigate.html file found"
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KiBot-outputs
        path: Generated

    - name: Disable Jekyll for GitHub Pages
      if: ${{ inputs.deploy-to-pages == 'true' }}
      run: |
        touch Generated/.nojekyll
      shell: bash

    - name: Deploy to GitHub Pages
      if: ${{ inputs.deploy-to-pages == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.pages-branch }}
        folder: Generated