name: KiBot
on:
  workflow_dispatch:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - 'config.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - 'config.kibot.yaml'

jobs:
  generate:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    permissions:
      contents: read
      actions: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Run KiBot Action
      uses: ./
      id: kibot

  # Deploy to GitHub Pages
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: generate

    steps:
    - uses: actions/checkout@v4

    - name: Retrieve results
      uses: actions/download-artifact@v4
      with:
        name: KiBot-outputs
        path: Generated

    - name: Disable Jekyll
      run: |
        touch Generated/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: Generated